services:
  ################################### UBUNTU
  rabbitmq-featured-ubuntu:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - "BASE_TAG=${BASE_TAG_UBUNTU}"
    cap_add:
      - ALL
    image: "rabbitmq-featured-ubuntu:${BASE_TAG_UBUNTU}"
    container_name: rabbitmq-featured-ubuntu
    hostname: rabbitmq-featured-ubuntu
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 10Gb
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # WEB UI
      - "15692:15692" # prometheus
      - "15675:15675" # web-mqtt
      - "1883:1883"   # mqtt
      - "5552:5552"   # stream
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
    - rabbitmq_featured      
  ###################################

  perftest:
    image: pivotalrabbitmq/perf-test:latest
    command: [
      "--uri", "amqp://guest:guest@rabbitmq-featured-ubuntu:5672/%2f",
      "-f", "persistent", 
      "-f", "mandatory",
      "--queue-pattern", "perf-test-%d",
      "--queue-pattern-from", "1",
      "--queue-pattern-to", "10",
      "--variable-size", "10:60",          #            10,00 B  |         0,01 kB |     0,00001 MB
      "--variable-size", "100:60",         #           100,00 B  |         0,10 kB |     0,00010 MB
      "--variable-size", "1000:60",        #         1.000,00 B  |         1,00 kB |     0,00100 MB
      "--variable-size", "10000:60",       #        10.000,00 B  |        10,00 kB |     0,01000 MB
      "--variable-size", "100000:60",      #       100.000,00 B  |       100,00 kB |     0,10000 MB
      "--variable-size", "1000000:60",     #     1.000.000,00 B  |     1.000,00 kB |     1,00000 MB
      "--variable-size", "2000000:60",     #     2.000.000,00 B  |     2.000,00 kB |     2,00000 MB
      "--variable-size", "5000000:60",     #     5.000.000,00 B  |     5.000,00 kB |     5,00000 MB
      "--variable-size", "8000000:60",     #     8.000.000,00 B  |     8.000,00 kB |     8,00000 MB
      "--variable-size", "10000000:60",    #    10.000.000,00 B  |    10.000,00 kB |    10,00000 MB
      "--producers", "10", 
      "--consumers", "20",
      "--heartbeat-sender-threads", "10",
      #"--rate", "100",
      #"--confirm", "3000",
      #"--multi-ack-every", "3000",
      #"--consumer-rate", "100"
      #"--qos", "3000",
      #"--auto-delete", "false"
      ]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 5Gb      
    networks:
    - rabbitmq_featured
  
  
  ################################### ALPINE
  # rabbitmq-featured-alpine:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - "BASE_TAG=${BASE_TAG_ALPINE}"
  #   image: "rabbitmq-featured-alpine:${BASE_TAG_ALPINE}"
  #   container_name: rabbitmq-featured-alpine
  #   hostname: rabbitmq-featured-alpine
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.50"
  #         memory: 150m
  #   ports:
  #     - "5676:5672"
  #     - "15676:15672"
  #     - "15696:15692"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "guest"
  #     RABBITMQ_DEFAULT_PASS: "guest"
  #   networks:
  #   - rabbitmq_featured  
  ###################################


networks:
  rabbitmq_featured:
    driver: bridge
    name: rabbitmq_featured

